GuardosEpitech/Guardos-mobile

- restoMobile/Router.tsx
- restoMobile/src/pages/ProfileScreen/Register/Register.tsx
- restoMobile/src/services/userCalls.ts
- visitorMobile/src/pages/ProfileScreen/Register/Register.tsx
Fix register for apps.
5. Run tests
> [FE] [MODIFY] fix register

- restoMobile/src/pages/ProfileScreen/Profile/Profile.styles.ts
- restoMobile/src/pages/ProfileScreen/Profile/Profile.tsx
- restoMobile/src/services/userCalls.ts
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.styles.ts
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
- visitorMobile/src/services/userCalls.ts
Give the user (visitor and resto) the possibility to delete their account in the apps.
5. Run tests
> [FE] [ADD] delete account button apps

- restoMobile/src/pages/ProfileScreen/Profile/NewProfile.styles.ts
- restoMobile/src/pages/ProfileScreen/Profile/NewProfile.tsx
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
Fix missing delete button due to merging mistakes.
5. Run tests
> [FE] [FIX] merge mistakes

- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
FIX deleting account in visitor app.
Deleting in visitor app was not working.
5. Run tests
> [APP] [FIX] fix delete account

- restoMobile/src/pages/ResetPasswordScreen/ResetPasswordScreen.styles.ts
- restoMobile/src/pages/ResetPasswordScreen/ResetPasswordScreen.tsx
- restoMobile/src/services/userCalls.ts
- visitorMobile/src/pages/ResetPasswordScreen/ResetPasswordScreen.styles.ts
- visitorMobile/src/pages/ResetPasswordScreen/ResetPasswordScreen.tsx
- visitorMobile/src/services/userCalls.ts
Added the mobile version for sending the forgot password link
> [BE] [ADD] Forgot Password

- restoMobile/package.json
- restoMobile/src/models/menuDesignsInterface.ts
- restoMobile/src/models/restaurantsInterfaces.ts
- restoMobile/src/pages/AddRestaurantScreen/AddRestaurantScreen.styles.ts
- restoMobile/src/pages/AddRestaurantScreen/AddRestaurantScreen.tsx
- restoMobile/src/pages/EditRestaurant/EditRestaurant.styles.ts
- restoMobile/src/pages/EditRestaurant/EditRestaurant.tsx
- restoMobile/src/pages/MyRestaurantsScreen/MyRestaurantsScreen.tsx
- restoMobile/src/services/restoCalls.ts
it is now possible to add menu design to the restaurant records
> [MOBILE] [ADD] MenuDesign changes functionality

- shared/models/dishInterfaces.ts
- visitorMobile/i18n/de.json
- visitorMobile/i18n/en.json
- visitorMobile/i18n/fr.json
- visitorMobile/src/components/Accordion/Accordion.styles.ts
- visitorMobile/src/components/Accordion/Accordion.tsx
- visitorMobile/src/components/Category/Category.styles.ts
- visitorMobile/src/components/Category/Category.tsx
- visitorMobile/src/components/DishCard/DishCard.styles.ts
- visitorMobile/src/components/DishCard/DishCard.tsx
- visitorMobile/src/models/dishesInterfaces.ts
- visitorMobile/src/pages/MapPage/MapPage.tsx
- visitorMobile/src/pages/MenuPage/MenuPage.tsx
- visitorMobile/src/services/menuCalls.ts
- visitorMobile/src/services/userCalls.ts
Hide dishes that dont fit the users food preferences, so its easier for them to scan the menu. However, also provide the option to extend the menu, so they can see all dishes. This is achieved by hiding the dishes behind an accordion that can be extended on click.
5. Run tests
> [FE] [MODIFY] filter menu according to user preference

- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/src/pages/AppIntro/AppIntro.tsx
> [APP] [FIX] Fix missing comma in i18n files and issue in Intro for android

- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/src/pages/AppIntro/AppIntro.tsx
- visitorMobile/src/pages/AppIntro/AppIntro.tsx
> [APP] [FIX] Fix issue in Intro for visitorMobile  for android

- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/src/pages/ProfileScreen/Profile/NewProfile.styles.ts
- restoMobile/src/pages/ProfileScreen/Profile/NewProfile.tsx
- restoMobile/src/services/imagesCalls.ts
- visitorMobile/i18n/de.json
- visitorMobile/i18n/en.json
- visitorMobile/i18n/fr.json
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.styles.ts
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
- visitorMobile/src/services/imageCalls.ts
Allow the user to upload, change, delete their profile picture (not just via link, but the picture itself).
5. Run tests
> [FE] [MODIFY] proper user profile picture management

- restoMobile/src/pages/ProfileScreen/Login/Login.tsx
> [FE] [DEL] remove third party login option

- restoMobile/src/pages/AddCategories/AddCategories.tsx
- restoMobile/src/pages/EditDishScreen/EditDish.style.ts
- restoMobile/src/pages/EditDishScreen/EditDish.tsx
- restoMobile/src/pages/MyDishesScreen/MyDishesScreen.tsx
add fix to categories to dishes
5. Run tests
> [FE] [MODIFY] Hotfix categories and dishes

- restoMobile/src/models/emailInterfaces.ts
- restoMobile/src/pages/FeatureRequest/FeatureRequest.tsx
- visitorMobile/src/models/emailInterfaces.ts
- visitorMobile/src/pages/FeatureRequest/FeatureRequest.tsx
Adds priority to feature request for premium users to both apps, test with BE of other repo on the same branch
5. Run tests
> [FE] [ADD] add priority to premium users

- visitorMobile/Router.tsx
adds the menu page to the visitor again 
5. Run tests
> [FE] [ADD] add menu page to router

- visitorMobile/babel.config.js
- visitorMobile/package.json
- visitorMobile/src/pages/MapPage/MapPage.styles.tsx
- visitorMobile/src/pages/MapPage/MapPage.tsx
Fixes the map screen and adds user location
5. Run tests
> [FE] [ADD] add GPS and fix map visitor

- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/src/components/TwoFactorAuth/TwoFactorAuthentification.tsx
- restoMobile/src/pages/ProfileScreen/Login/Login.tsx
- restoMobile/src/pages/ProfileScreen/Profile/NewProfile.styles.ts
- restoMobile/src/pages/ProfileScreen/Profile/NewProfile.tsx
- restoMobile/src/services/profileCalls.ts
- restoMobile/src/services/userCalls.ts
> [FE] [ADD] add two factor auth for restaurants

- restoMobile/Router.tsx
- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/src/pages/ProfileScreen/Profile/NewProfile.tsx
- restoMobile/src/pages/UserInsights/UserInsinghts.styles.ts
- restoMobile/src/pages/UserInsights/UserInsinghts.tsx
- restoMobile/src/services/restoCalls.ts
As a restaurant owner, i want to know how I can improve myself, 
to do so, I now can see how many customors I could have and which food preferences they have
5. Run tests
> [FE] [ADD] add user insights 

- shared/models/communicationInterfaces.ts
- shared/models/locationInterfaces.ts
- visitorMobile/src/pages/MapPage/MapPage.styles.tsx
- visitorMobile/src/pages/MapPage/MapPage.tsx
- visitorMobile/src/pages/RestaurantScreen/RestaurantScreen.styles.ts
- visitorMobile/src/pages/RestaurantScreen/RestaurantScreen.tsx
> [FE] [FIX] range filter and darkmode filter

- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
> [FE] [MODIFY] link to menu from fav resto

- restoMobile/Router.tsx
- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/src/pages/Guides/Accordion.tsx
- restoMobile/src/pages/Guides/GuidesPage.tsx
- visitorMobile/Router.tsx
- visitorMobile/i18n/de.json
- visitorMobile/i18n/en.json
- visitorMobile/i18n/fr.json
- visitorMobile/package.json
- visitorMobile/src/models/restaurantsInterfaces.ts
- visitorMobile/src/pages/Guides/Accordion.tsx
- visitorMobile/src/pages/Guides/GuidesPage.tsx
- visitorMobile/src/pages/RestaurantScreen/RestaurantScreen.styles.ts
- visitorMobile/src/pages/RestaurantScreen/RestaurantScreen.tsx
- visitorMobile/src/services/profileCalls.ts
> [FE] [ADD] group filter + guides

- restoMobile/Router.tsx
- restoMobile/src/pages/AddCategories/AddCategories.styles.ts
- restoMobile/src/pages/AddCategories/AddCategories.tsx
- restoMobile/src/pages/DishDiscountPage/DishDiscountPage.tsx
- shared/models/categoryInterfaces.ts
> [FE] [FIX] categories and dish discount

- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/src/pages/MenuPage/MenuPage.styles.ts
- restoMobile/src/pages/MenuPage/MenuPage.tsx
- visitorMobile/i18n/de.json
- visitorMobile/i18n/en.json
- visitorMobile/i18n/fr.json
- visitorMobile/src/pages/MenuPage/MenuPage.styles.ts
- visitorMobile/src/pages/MenuPage/MenuPage.tsx
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
Filter out empty categories in menu. Show no menu message in case no dishes exist for that resto. Visitor: Add no favorites message in case no resto or dish is saved yet.
5. Run tests
> [FE] [ADD] don't display empty categories and show no objects message

- visitorMobile/src/pages/RestaurantScreen/RestaurantScreen.tsx
Previously, visitors could add another saved filter with the same name as another saved filter, even if there limit was reached.
5. Run tests
> [FE] [FIX] prevent saved filters with same name

- visitorMobile/Router.tsx
> [FE] [FIX] fix navigation forgot password visitor

- restoMobile/src/pages/Guides/Accordion.tsx
- restoMobile/src/pages/Guides/GuidesPage.tsx
- visitorMobile/src/pages/Guides/Accordion.tsx
- visitorMobile/src/pages/Guides/GuidesPage.tsx
Addition of the darkMode for the Guide as it was missing for the KO
5. Run tests
> [APP] [ADD] Added darkMode for the guide page on both app

- restoMobile/src/pages/ImprintPage/ImprintPage.tsx
- restoMobile/src/pages/PrivacyPage/PrivacyPage.tsx
- visitorMobile/src/pages/ContactUs/ContactUs.tsx
- visitorMobile/src/pages/ImprintPage/ImprintPage.tsx
- visitorMobile/src/pages/PrivacyPage/PrivacyPage.tsx
> [FE] [FIX] removed fake phone number

- shared/models/communicationInterfaces.ts
- shared/models/restaurantInterfaces.ts
- visitorMobile/src/models/restaurantsInterfaces.ts
- visitorMobile/src/pages/MenuPage/MenuPage.styles.ts
- visitorMobile/src/pages/MenuPage/MenuPage.tsx
- visitorMobile/src/pages/RestaurantScreen/RestaurantScreen.tsx
Fix visitor app group filters.
5. Run tests
> [FE] [FIX] Fix group filter

- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/src/pages/ProfileScreen/Login/Login.styles.ts
- restoMobile/src/pages/ProfileScreen/Login/Login.tsx
- restoMobile/src/services/userCalls.ts
- visitorMobile/i18n/de.json
- visitorMobile/i18n/en.json
- visitorMobile/i18n/fr.json
- visitorMobile/src/pages/ProfileScreen/Login/Login.styles.ts
- visitorMobile/src/pages/ProfileScreen/Login/Login.tsx
- visitorMobile/src/services/userCalls.ts
add send resend verify email on mobile 
5. Run tests
> Fix verify email

- restoMobile/Router.tsx
- restoMobile/src/components/DishCard/DishCard.tsx
- restoMobile/src/components/ProductForm/ProductForm.tsx
- restoMobile/src/pages/EditDishScreen/EditDish.tsx
> [FE] [MODIFY] Path specific problem + delete of allergen

- visitorMobile/src/pages/ProfileScreen/Login/Login.tsx
> [FE] [FIX] user data format

- visitorMobile/src/components/DishCard/DishCard.tsx
- visitorMobile/src/components/RestaurantCard/RestaurantCard.tsx
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
update favourite lists on profile page, when removing a favourite object (resto or dish) on that page
5. Run tests
> [FE] [FIX] update favourite lists after an item was removed

- visitorMobile/src/pages/ProfileScreen/Profile/Profile.styles.ts
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
Dialog action buttons were out of bound. Fixed with this PR.
5. Run tests
> [FE] [FIX] keep add ingredient dialog buttons within dialog bounds

- visitorMobile/src/pages/ProfileScreen/Profile/Profile.styles.ts
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
- visitorMobile/src/services/ingredientsCalls.ts
Fix error when adding disliked ingredient to DB ('Ingredient not found' button).
5. Run tests
> [FE] [FIX] adding disliked ingredient to db via profile

- visitorMobile/src/pages/ProfileScreen/Profile/Profile.styles.ts
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
User can see to what restaurant a favourite dish belongs (in profile page, fav dish tab) with reference to the resto menu. This way, they can direct to the resto menu from the fav dish groups.
5. Run tests
> [FE] [ADD] reference to resto for fav dish in profile page

- restoMobile/src/pages/AddRestaurantScreen/AddRestaurantScreen.tsx
- restoMobile/src/pages/EditDishScreen/EditDish.tsx
- restoMobile/src/pages/EditRestaurant/EditRestaurant.tsx
- restoMobile/src/pages/ProfileScreen/Profile/NewProfile.tsx
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
Fixed: couldnt add images in apps. Profile used wrong userToken.
5. Run tests
> [FE] [FIX] image management

- restoMobile/src/pages/MenuPage/MenuPage.tsx
- visitorMobile/src/components/Header.tsx
- visitorMobile/src/pages/MenuPage/MenuPage.styles.ts
- visitorMobile/src/pages/MenuPage/MenuPage.tsx
Add resto name to menu (resto and visitor app), so the user sees the reference.
5. Run tests
> [FE] [FIX] show resto name in menu

- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/src/pages/AddCategories/AddCategories.tsx
Fix missing translation in the restoMobile app 
5. Run tests
> [APP] [FIX] Fix missing i18n for delete categories

- restoMobile/src/pages/EditDishScreen/EditDish.tsx
Adding or changing an image is an immediate request. As long as the object is not created, this will not work. Therefore, the image was removed from the add dish form.
5. Run tests
> [FE] [FIX] remove image from add dish form

- restoMobile/src/pages/Guides/Accordion.tsx
- restoMobile/src/pages/Guides/GuidesPage.tsx
- visitorMobile/src/components/RestaurantCard/RestaurantCard.styles.ts
- visitorMobile/src/components/RestaurantCard/RestaurantCard.tsx
- visitorMobile/src/services/restoCalls.ts
Fix Guide that wasn't super readable in darkMode 
And addition of the detail pop-up
5. Run tests
> [APP] [ADD] Addition of a details pop-up that was missing

- visitorMobile/src/pages/MapPage/MapPage.tsx
- visitorMobile/src/pages/RestaurantScreen/RestaurantScreen.tsx
- visitorMobile/src/services/categorieCalls.ts
- Both filter now have categorie search option
Like in the web we want to show all categories from the restaurants.
same options in web & app
5. Run tests
> [FE][ADD] apps can now fetch categories

- restoMobile/src/pages/Payment/PaymentPage.tsx
- restoMobile/src/services/userCalls.ts
- visitorMobile/src/pages/Payment/PaymentPage.tsx
- visitorMobile/src/services/userCalls.ts
fix payment issues
5. Run tests
> [APP] [ADD] Fix payment in app

- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/src/pages/AddRestaurantScreen/AddRestaurantScreen.tsx
- restoMobile/src/pages/FeatureRequest/FeatureRequest.tsx
- restoMobile/src/pages/MenuPage/MenuPage.styles.ts
- restoMobile/src/pages/MenuPage/MenuPage.tsx
- restoMobile/src/pages/QRCodeEngin/QRCodeEngin.styles.ts
- restoMobile/src/pages/QRCodeEngin/QRCodeEngin.tsx
- restoMobile/src/services/qrcodeCall.ts
- restoMobile/src/services/restoCalls.ts
- visitorMobile/i18n/de.json
- visitorMobile/i18n/en.json
- visitorMobile/i18n/fr.json
- visitorMobile/src/pages/FeatureRequest/FeatureRequest.tsx
- visitorMobile/src/pages/Payment/PaymentPage.tsx
> Back log alban nov

- shared/models/communicationInterfaces.ts
- visitorMobile/Router.tsx
- visitorMobile/src/pages/MapPage/MapPage.tsx
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
- visitorMobile/src/pages/RestaurantScreen/RestaurantScreen.tsx
Fix the issue where user allergens where not directly applied when launching the app/refresh the page and fixes an issue where the filter was not correctly shared between list and map view
5. Run tests
> [FE] [FIX] Fix resto filter allergen

- visitorMobile/src/pages/MapPage/MapPage.tsx
- visitorMobile/src/pages/RestaurantScreen/RestaurantScreen.tsx
> [FE] [FIX] add group profiles in map filter

- restoMobile/src/pages/MenuPage/MenuPage.styles.ts
> [FE] [MODIFY] Fixed menu design

- restoMobile/src/pages/AddRestaurantScreen/AddRestaurantScreen.tsx
Fix the issue described bellow .
No user is redirected to the resto page with the new resto already here 
If add resto, we doesnt show it 
1. add resto
2. you have to reload 
4. Review the changes on GitHub
5. Execute locally / in testing environment
6. Run tests
7. Linting & Formatting
8. Submit Feedback
> [APP] [FIX] Fix an issue where you had to refresh for a new resto to appear

- visitorMobile/src/pages/RestaurantScreen/RestaurantScreen.tsx
> [FE] [FIX] adjust user token usage

- restoMobile/src/pages/ResetPasswordScreen/ResetPasswordScreen.tsx
> [FE] [FIX] forgot password popup missing translation

- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/src/pages/UserInsights/UserInsinghts.tsx
- visitorMobile/i18n/de.json
- visitorMobile/i18n/en.json
- visitorMobile/i18n/fr.json
- visitorMobile/src/components/DishCard/DishCard.tsx
- visitorMobile/src/pages/MapPage/MapPage.tsx
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
- visitorMobile/src/pages/RestaurantScreen/RestaurantScreen.tsx
- added translation for visitor at: dishcard, map view, profile and restaurantscreen
- added translation for restaurant at user insights 
- internationalise our app
5. Run tests
> [FE] [ADD] add translation for allergens 

- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/src/components/DishCard/DishCard.tsx
- restoMobile/src/components/ModalConfirm/ModalConfirm.tsx
- restoMobile/src/components/ProductCard/ProductCard.tsx
- restoMobile/src/components/RestaurantCard.tsx
- restoMobile/src/pages/AddRestoChain/AddRestoChain.tsx
> [FE] [ADD] delete object confirmation dialog

- visitorMobile/src/components/RestaurantCard/RestaurantCard.styles.ts
- visitorMobile/src/components/RestaurantCard/RestaurantCard.tsx
Add missing share menu for the visitorMobile 
5. Run tests
> [APP] [ADD] Adition of share button for visitorMobile

- restoMobile/src/pages/MyRestaurantsScreen/MyRestaurantsScreen.tsx
- visitorMobile/src/pages/RestaurantScreen/RestaurantScreen.tsx
Hide ads for payed users
5. Run tests
> [FE] [FIX] Fix ads premium

- visitorMobile/src/pages/RatingPage/Rating.tsx
> fix rating

- restoMobile/src/pages/AddCategories/AddCategories.tsx
- restoMobile/src/pages/AddRestoChain/AddRestoChain.tsx
- restoMobile/src/pages/DishComboPage/DishComboPage.tsx
- restoMobile/src/pages/MenuPage/MenuPage.tsx
- restoMobile/src/pages/MyDishesScreen/MyDishesScreen.tsx
- restoMobile/src/pages/MyProductsScreen/MyProductsScreen.tsx
- restoMobile/src/pages/MyRestaurantsScreen/MyRestaurantsScreen.tsx
- restoMobile/src/pages/ProfileScreen/Profile/NewProfile.tsx
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
> Bug/update-data Resto and vistor refresh at drag and down when necessary

- visitorMobile/src/pages/RatingPage/Rating.tsx
- visitorMobile/src/pages/UserReviewPage/UserReview.tsx
> Solved rating

- restoMobile/src/pages/AddCategories/AddCategories.tsx
> [FE] [FIX] add category if resto has none yet

- restoMobile/src/pages/DishDiscountPage/DishDiscountPage.tsx
> [FE] [FIX] dont allow 0 discount

- restoMobile/src/pages/EditRestaurant/EditRestaurant.tsx
- restoMobile/src/services/restoCalls.ts
Couldnt edit resto name. This PR fixes it.
5. Run tests
> [FE] [FIX] enable resto name editing

- restoMobile/src/pages/EditDishScreen/EditDish.tsx
editing of dish name was disabled by default. This PR enables editing.
5. Run tests
> [FE] [MODIFY] make dish name editable

- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/src/pages/FeatureRequest/FeatureRequest.styles.ts
- restoMobile/src/pages/FeatureRequest/FeatureRequest.tsx
- restoMobile/src/pages/UserSupport/UserSupport.styles.ts
- restoMobile/src/pages/UserSupport/UserSupport.tsx
- visitorMobile/i18n/de.json
- visitorMobile/i18n/en.json
- visitorMobile/i18n/fr.json
- visitorMobile/src/pages/FeatureRequest/FeatureRequest.styles.ts
- visitorMobile/src/pages/FeatureRequest/FeatureRequest.tsx
- visitorMobile/src/pages/UserSupport/UserSupport.styles.ts
- visitorMobile/src/pages/UserSupport/UserSupport.tsx
Add missing error messages and have consistent error messages in the user support and feature request forms.
5. Run tests
> [FE] [MODIFY] consistent error messages user support and feature request

- visitorMobile/i18n/de.json
- visitorMobile/i18n/en.json
- visitorMobile/i18n/fr.json
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.styles.ts
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
Previously, the allergen and disliked ingredient popup in the profile page was not scrollable, making it imporssible to select some allergens/disliked ingredients for the user. The popup was replaced with another one.
5. Run tests
> [FE] [FIX] make all allergens and disliked ingredients selectable

- visitorMobile/src/pages/ProfileScreen/Profile/Profile.styles.ts
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
Previously: have at least 4 fav objects (resto OR dish) registered -> go to profile page -> scroll to fav table -> go to next page -> remove all objects of that page (so that only 3 are left) -> didnt automatically switch to previous page, but showed an empty page.
This PR changes that -> automatically decreases page if no elements are left in current one anymore.
5. Run tests
> [FE] [MODIFY] pagination: decrease page size on empty page

- restoMobile/src/components/DishCard/DishCard.style.ts
- restoMobile/src/components/DishCard/DishCard.tsx
- restoMobile/src/components/ProductCard/ProductCard.styles.ts
- restoMobile/src/components/ProductCard/ProductCard.tsx
- visitorMobile/src/components/DishCard/DishCard.styles.ts
- visitorMobile/src/components/DishCard/DishCard.tsx
Show allergens tags on product and dish cards in product overview page / dish over view page and menu page..
5. Run tests
> [FE] [MODIFY] show allergens on products and dishes

- restoMobile/src/pages/AddCategories/AddCategories.tsx
- restoMobile/src/pages/AddRestoChain/AddRestoChain.tsx
- restoMobile/src/pages/MyDishesScreen/MyDishesScreen.tsx
- restoMobile/src/pages/MyProductsScreen/MyProductsScreen.tsx
> [APP][FIX] Fix pages with white block when in dark mode

- visitorMobile/src/pages/MapPage/MapPage.styles.tsx
- visitorMobile/src/pages/MapPage/MapPage.tsx
> [ADD] [APP] Added share button in the map detail view

- restoMobile/src/pages/ProfileScreen/Profile/NewProfile.tsx
Deleted default menu desing in Account Page
> [FE] [MODIFY] Delete default Menu Design

- restoMobile/src/pages/AddRestaurantScreen/AddRestaurantScreen.tsx
- restoMobile/src/pages/ProfileScreen/Profile/NewProfile.tsx
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
Resto only:
- resto form: phone number and resto chain not saved during add form
Both apps:
- can select subscription without payment method registered
> [FE] [MODIFY] changed Resto Forms & Subscription Button for Resto and Visitor

- restoMobile/src/components/DishCard/DishCard.tsx
- restoMobile/src/pages/MyDishesScreen/MyDishesScreen.tsx
Dishes Page on resto app --> if has dish combo --> click to extend --> previously dish card didnt actually extend --> fix in PR
5. Run tests
> [FE] [MODIFY] show dish combo on extend

- restoMobile/src/components/DishCard/DishCard.tsx
- restoMobile/src/pages/EditDishScreen/EditDish.tsx
- restoMobile/src/services/dishCalls.ts
Update dish list for dish combos on dish delete. Also adjustments regarding dish name update related to https://github.com/GuardosEpitech/Guardos/pull/256
5. Run tests
> [FE] [MODIFY] fix syncing product data

- restoMobile/src/pages/MyDishesScreen/MyDishesScreen.tsx
- restoMobile/src/pages/MyProductsScreen/MyProductsScreen.tsx
> [FIX] [APP] Changed AddButton on Dished & Product page to bottom of the screen not of the list

- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/src/components/ProductForm/ProductForm.styles.ts
- restoMobile/src/components/ProductForm/ProductForm.tsx
- restoMobile/src/services/ingredientsCalls.ts
use db ingredients for product form. allow adding new ingredients.
5. Run tests
> [FE] [MODIFY] use db ingredients for product form

- restoMobile/src/components/DishCard/DishCard.tsx
- restoMobile/src/pages/EditDishScreen/EditDish.tsx
- restoMobile/src/pages/MyDishesScreen/MyDishesScreen.tsx
- visitorMobile/src/components/DishCard/DishCard.tsx
Previously, the combo was shown for deleted dishes. Key mapping on dishes page wasnt working correctly.
5. Run tests
> [FE] [MODIFY] only show combo banner on valid combos

- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/src/components/ProductForm/ProductForm.tsx
- restoMobile/src/pages/AddCategories/AddCategories.tsx
- restoMobile/src/pages/AddRestaurantScreen/AddRestaurantScreen.tsx
- restoMobile/src/pages/DishComboPage/DishComboPage.tsx
- restoMobile/src/pages/EditDishScreen/EditDish.tsx
- restoMobile/src/pages/EditRestaurant/EditRestaurant.tsx
Dont allow objects with same name per user: restaurants, categories (per resto, not user), products,
Also, load dishes per user for combo options instead of load dishes per one resto (as we can assign dishes to several resto, it resulted in an incomplete selection).
5. Run tests
> [FE] [MODIFY] prevents objects with same name per user

- restoMobile/src/pages/EditDishScreen/EditDish.style.ts
- restoMobile/src/pages/EditDishScreen/EditDish.tsx
- restoMobile/src/services/dishCalls.ts
Fix add, edit, delete dish (some bugs with several restos selected) and limit category selection to one in dish form.
5. Run tests
> [FE] [MODIFY] fix add, edit, delete dish and limit category selection

- restoMobile/src/components/RestaurantCard.tsx
- restoMobile/src/pages/EditRestaurant/EditRestaurant.tsx
- restoMobile/src/pages/MyRestaurantsScreen/MyRestaurantsScreen.tsx
- restoMobile/src/services/imagesCalls.ts
- restoMobile/src/services/restoCalls.ts
we now use the id to get // edit // delete restaurants 
We now can have restaurants with the same name because we only look at the id 
easify 
5. Run tests
> [FE] [FIX] use ID instead of name for restaurant

- visitorMobile/src/pages/ProfileScreen/Profile/Profile.styles.ts
- visitorMobile/src/pages/ProfileScreen/Profile/Profile.tsx
Fix issue with the modals for allergen & disliked ingredient 
Allergens and disliked ingredient modals where not scrolable .
5. Run tests
> [APP][FIX] Fix issue with the modals for allergen & disliked ingredient 

- restoMobile/src/pages/AddCategories/AddCategories.tsx
- restoMobile/src/pages/AddRestoChain/AddRestoChain.tsx
- restoMobile/src/pages/EditRestaurant/EditRestaurant.styles.ts
- restoMobile/src/pages/EditRestaurant/EditRestaurant.tsx
Fix issue with dark on dark font that make it hard to read in the categorie page
And missing DarkMode in the resto form 
5. Run tests
> [APP][FIX] Fix mutliples issue with DarkMode in RestoForm & AddCategorie

- visitorMobile/src/components/RestaurantCard/RestaurantCard.tsx
- visitorMobile/src/pages/MapPage/MapPage.tsx
- visitorMobile/src/pages/RatingPage/Rating.tsx
Fix issue with review where it was crashing when comming from the map view & issue when comment was empty
5. Run tests
> [APP][FIX] Fix issue with review 

- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/src/pages/QRCodeEngin/QRCodeEngin.tsx
- restoMobile/src/services/productCalls.ts
add complete products, not only names
we want to add products not names
5. Run tests
> [FE] [FIX] change barcode scanner

- restoMobile/src/pages/AddCategories/AddCategories.tsx
- shared/models/categoryInterfaces.ts
adds the code for the edit category case
5. Run tests
> [FE] [MODIFY] fix edit category remap

- restoMobile/i18n/de.json
- restoMobile/i18n/en.json
- restoMobile/i18n/fr.json
- restoMobile/package.json
- restoMobile/src/pages/AddRestaurantScreen/AddRestaurantScreen.styles.ts
- restoMobile/src/pages/AddRestaurantScreen/AddRestaurantScreen.tsx
- restoMobile/src/pages/EditRestaurant/EditRestaurant.styles.ts
- restoMobile/src/pages/EditRestaurant/EditRestaurant.tsx
- restoMobile/src/pages/QRCodeEngin/QRCodeEngin.tsx
- restoMobile/src/pages/UserInsights/UserInsinghts.tsx
> Alban intern ext def

- restoMobile/src/components/DishCard/DishCard.tsx
- restoMobile/src/pages/EditRestaurant/EditRestaurant.tsx
- restoMobile/src/services/dishCalls.ts
- visitorMobile/src/components/DishCard/DishCard.tsx
- visitorMobile/src/components/RestaurantCard/RestaurantCard.tsx
- visitorMobile/src/pages/MapPage/MapPage.tsx
- visitorMobile/src/pages/RatingPage/Rating.tsx
- visitorMobile/src/services/menuCalls.ts
- visitorMobile/src/services/ratingCalls.ts
Adjust according to BE changes. Only merge once https://github.com/GuardosEpitech/Guardos/pull/275 is merged!
5. Run tests
> [FE] [MODIFY] adjust to BE call changes

- visitorMobile/src/pages/RestaurantScreen/RestaurantScreen.tsx
> [APP][FIX] Fix issue with the rating filter in the resto list-view

- restoMobile/src/pages/MenuPage/MenuPage.tsx
Scrolling was not possible in resto app menu before.
5. Run tests
> [FE] [MODIFY] fix menu scrolling

- visitorMobile/src/components/DishCard/DishCard.tsx
Pass correct id for fetching dish combinations on menus on visitor mobile.
5. Run tests
> [FE] [MODIFY] hand resto Id instead of name for dish combos

- restoMobile/Router.tsx
- restoMobile/src/pages/AddRestaurantScreen/AddRestaurantScreen.styles.ts
- restoMobile/src/pages/AddRestaurantScreen/AddRestaurantScreen.tsx
- restoMobile/src/pages/DishComboPage/DishComboPage.style.ts
> [APP] [FIX] Fix darkMode for the restoCombo and openingHou

- visitorMobile/src/pages/RestaurantScreen/RestaurantScreen.tsx
fix for own allergens are not applied completely in resto list search
fix for: filter -> on delete -> allergens are not reset
We now have the same filter behavior in web and app.
Also we can clear the filter correctly
5. Run tests
> [FE][FIX] fix allergen delete bug
